function Invoke-CIPPStandardallowOTPTokens {
    <#
    .FUNCTIONALITY
        Internal
    .COMPONENT
        (APIName) allowOTPTokens
    .SYNOPSIS
        (Label) Set Microsoft Authenticator OTP state
    .DESCRIPTION
        (Helptext) Enables or disables the OTP code generated by the Microsoft Authenticator app. Useful for NPS extension VPN authentication. CISA MS.AAD.3.3v2 recommends disabling this setting.
        (DocsDescription) Enables or disables the Microsoft Authenticator OTP token generator. Useful for using the NPS extension as MFA on VPN clients.
    .NOTES
        CAT
            Entra (AAD) Standards
        TAG
            "EIDSCA.AM02"
            "EIDSCAAM02"
        EXECUTIVETEXT
            Controls one-time password generation through Microsoft Authenticator app. Disabling is recommended by CISA MS.AAD.3.3v2 unless needed for specific scenarios such as VPN access via NPS extension.
        ADDEDCOMPONENT
            {"type":"Select","label":"OTP State","name":"standards.allowOTPTokens.State","values":[{"label":"Enabled","value":"true"},{"label":"Disabled","value":"false"}]}
        IMPACT
            Low Impact
        ADDEDDATE
            2023-12-06
        POWERSHELLEQUIVALENT
            Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration
        RECOMMENDEDBY
            "CISA"
        UPDATECOMMENTBLOCK
            Run the Tools\Update-StandardsComments.ps1 script to update this comment block
    .LINK
        https://docs.cipp.app/user-documentation/tenant/standards/list-standards
    #>
    param($Tenant, $Settings)

    try {
        $CurrentInfo = New-GraphGetRequest -uri 'https://graph.microsoft.com/beta/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/microsoftAuthenticator' -tenantid $Tenant
    } catch {
        $ErrorMessage = Get-NormalizedError -Message $_.Exception.Message
        Write-LogMessage -API 'Standards' -Tenant $Tenant -Message "Could not get the allowOTPTokens state for $Tenant. Error: $ErrorMessage" -Sev Error
        return
    }

    $WantedState = if ($Settings.State -eq 'false') { $false } else { $true }
    $StateText = if ($WantedState) { 'enabled' } else { 'disabled' }
    $StateCorrect = $CurrentInfo.isSoftwareOathEnabled -eq $WantedState

    # Input validation
    if ($null -eq $Settings.State -and ($Settings.remediate -eq $true -or $Settings.alert -eq $true)) {
        Write-LogMessage -API 'Standards' -tenant $Tenant -message 'allowOTPTokens: Invalid state parameter set' -sev Error
        Return
    }

    if ($Settings.remediate -eq $true) {
        if ($StateCorrect) {
            Write-LogMessage -API 'Standards' -tenant $Tenant -message "MS Authenticator OTP tokens is already $StateText." -sev Info
        } else {
            try {
                # Remove number matching from featureSettings because this is now Microsoft enforced
                $CurrentInfo.featureSettings.PSObject.Properties.Remove('numberMatchingRequiredState')
                $CurrentInfo.isSoftwareOathEnabled = $WantedState
                $body = ConvertTo-Json -Depth 3 -Compress -InputObject $CurrentInfo
                $null = New-GraphPostRequest -tenantid $Tenant -Uri 'https://graph.microsoft.com/beta/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/microsoftAuthenticator' -Type patch -Body $body -ContentType 'application/json'
                Write-LogMessage -API 'Standards' -tenant $Tenant -message "MS Authenticator OTP tokens has been $StateText." -sev Info
            } catch {
                $ErrorMessage = Get-CippExceptionMessage -Exception $_
                Write-LogMessage -API 'Standards' -tenant $Tenant -message "Failed to set MS Authenticator OTP tokens to $StateText. Error: $($ErrorMessage.NormalizedError)" -sev Error -LogData $ErrorMessage
            }
        }
    }

    if ($Settings.alert -eq $true) {
        if ($StateCorrect) {
            Write-LogMessage -API 'Standards' -tenant $Tenant -message "MS Authenticator OTP tokens is $StateText." -sev Info
        } else {
            Write-StandardsAlert -message "MS Authenticator OTP tokens is not $StateText." -object $CurrentInfo -tenant $tenant -standardName 'allowOTPTokens' -standardId $Settings.standardId
            Write-LogMessage -API 'Standards' -tenant $Tenant -message "MS Authenticator OTP tokens is not $StateText." -sev Info
        }
    }

    if ($Settings.report -eq $true) {
        $CurrentValue = @{ isSoftwareOathEnabled = $CurrentInfo.isSoftwareOathEnabled }
        $ExpectedValue = @{ isSoftwareOathEnabled = $WantedState }
        Set-CIPPStandardsCompareField -FieldName 'standards.allowOTPTokens' -CurrentValue $CurrentValue -ExpectedValue $ExpectedValue -TenantFilter $Tenant
        Add-CIPPBPAField -FieldName 'MSAuthenticator' -FieldValue $CurrentInfo.isSoftwareOathEnabled -StoreAs bool -Tenant $Tenant
    }
}
