# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Powershell project to Azure Function App - cipp6xxrn

on:
  push:
    branches:
      - test/travel-ca-policy
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cipp6xxrn__staging
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CBB35D647C1F46BE978786CC12EE4D0A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_24BE66E7123F4ABAB31DE96C69C13D46 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B871FA51A3E2416C9C4F0BF3D319B15E }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'cipp6xxrn'
          slot-name: 'staging'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          
